local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "USP Tactical";
    ITEM.cost = 600;
    ITEM.model = "models/weapons/w_pist_usp_silencer.mdl";
    ITEM.weight = 1;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_usp";
    ITEM.business = true;
    ITEM.batch = 1;
    ITEM.description = "Heckler & Koch USP chambered in .40 Smith & Wesson, it has a tactical flashlight and sound suppressor attached to the threaded barrel.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = true;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_L_Thigh";
    ITEM.attachmentOffsetAngles = Angle(108.4, 0, 0);
    ITEM.attachmentOffsetVector = Vector(4.95, -4.24, 3.03);
ITEM:Register();