local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "Steyr Scout Rifle";
    ITEM.cost = 2500;
    ITEM.model = "models/weapons/w_snip_scout.mdl";
    ITEM.weight = 3.5;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_scout";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "A versatile 7.62 light bolt-action rifle, created in Austria, not commonly used by pre-war forces.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
    ITEM.attachmentOffsetAngles = Angle(0, 18, 0);
    ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();