local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "IMI Galil";
    ITEM.cost = 1500;
    ITEM.model = "models/weapons/w_rif_galil.mdl";
    ITEM.weight = 4;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_galil";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "The IMI Galil, created by the Israel Military Indistries, it was built to be a successor to the AK, chambered in 5.56x45mm, it was used as a good military rifle.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
    ITEM.attachmentOffsetAngles = Angle(0, 18, 0);
    ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();