local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "P228";
    ITEM.cost = 500;
    ITEM.model = "models/weapons/w_pist_p228.mdl";
    ITEM.weight = 1;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_p228";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "The SIG Sauer P228, chambered in nine millimeter, it was created in Germany, issued to many operators around the world before the war.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_L_Thigh";
    ITEM.attachmentOffsetAngles = Angle(108.4, 0, 0);
    ITEM.attachmentOffsetVector = Vector(4.95, -4.24, 3.03);
ITEM:Register();