local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "Steyr TMP";
    ITEM.cost = 1200;
    ITEM.model = "models/weapons/w_smg_tmp.mdl";
    ITEM.weight = 3.8;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_tmp";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "The Steyr TMP is a select fire nine millimeter machine pistol, manufactured in Austria, it's not a common firearm.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_L_Thigh";
    ITEM.attachmentOffsetAngles = Angle(108.4, 0, 0);
    ITEM.attachmentOffsetVector = Vector(4.95, -4.24, 3.03);
ITEM:Register();