local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "FN P90";
    ITEM.cost = 2800;
    ITEM.model = "models/weapons/w_smg_p90.mdl";
    ITEM.weight = 3;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_p90";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "The FN P90, chambered in the FN 5.7x28mm round, a miniture rifle bullet, packed into a large 50 round magazine. The FN P90 was created in Belgium during the 1980s.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
    ITEM.attachmentOffsetAngles = Angle(0, 18, 0);
    ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();