local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "Steyr AUG";
    ITEM.cost = 4000;
    ITEM.model = "models/weapons/w_rif_aug.mdl";
    ITEM.weight = 3.6;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_aug";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "The Steyr AUG, created in Austria in the 1960s, a NATO bullpup rifle chambered in 5.56x45mm, comes with a scope built on for longer ranged engagements.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
    ITEM.attachmentOffsetAngles = Angle(0, 18, 0);
    ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();