local ITEM = Clockwork.item:New("weapon_base");
	ITEM.name = "Benelli M3";
	ITEM.cost = 1600;
	ITEM.model = "models/weapons/w_shot_m3super90.mdl";
	ITEM.weight = 3.4;
	ITEM.uniqueID = "rcs_m3";
	ITEM.business = false;
	ITEM.batch = 1;
	ITEM.access = "V";
	ITEM.description = "Strong 12 Gauge pump-action shotgun created in Italy by a quality company, used by many law enforcement and military forces before the war.";
	ITEM.isAttachment = true;
	ITEM.hasFlashlight = false;
	ITEM.loweredOrigin = Vector(3, 0, -4);
	ITEM.loweredAngles = Angle(0, 45, 0);
	ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
	ITEM.attachmentOffsetAngles = Angle(0, 16, 0);
	ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();