local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "M4A1";
    ITEM.cost = 1500;
    ITEM.model = "models/weapons/w_rif_m4a1.mdl";
    ITEM.weight = 3.4;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_m4a1";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "The M4A1, commonly used as a standard issue prewar military rifle. Chambered in 5.56x45mm, it was designed in 1994 by the United States of America.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = true;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
    ITEM.attachmentOffsetAngles = Angle(0, 18, 0);
    ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();