local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "SG552";
    ITEM.cost = 1800;
    ITEM.model = "models/weapons/w_rif_sg552.mdl";
    ITEM.weight = 3.4;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_sg552";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "The Sturmgewehr 552, created in Switzerland in the 1070s, a common military assault rifle, chambered in 5.56x45mm, it's quite a reliable weapon.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
    ITEM.attachmentOffsetAngles = Angle(0, 18, 0);
    ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();