local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "H&K UMP-45";
    ITEM.cost = 2500;
    ITEM.model = "models/weapons/w_smg_ump45.mdl";
    ITEM.weight = 2.5;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_ump";
    ITEM.business = false;
    ITEM.batch = 1;
    ITEM.description = "The UMP-45, a blowback operated submachine gun chambered in .45 ACP, designed by Heckler & Kock in the 1990s, originated in Germany as a very reliable SMG.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
    ITEM.attachmentOffsetAngles = Angle(0, 18, 0);
    ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();