local ITEM = Clockwork.item:New("weapon_base");
    ITEM.name = "MAC-10";
    ITEM.cost = 800;
    ITEM.model = "models/weapons/w_smg_mac10.mdl";
    ITEM.weight = 2;
    ITEM.access = "V";
    ITEM.uniqueID = "rcs_mac10";
    ITEM.business = true;
    ITEM.batch = 1;
    ITEM.description = "The MAC-10 or the Military Armament Corporation Model 10, is a fully automatic machine pistol designed in the 1970s in America, it's chambered in .380 ACP.";
    ITEM.isAttachment = true;
    ITEM.hasFlashlight = false;
    ITEM.loweredOrigin = Vector(3, 0, -4);
    ITEM.loweredAngles = Angle(0, 45, 0);
    ITEM.attachmentBone = "ValveBiped.Bip01_Spine";
    ITEM.attachmentOffsetAngles = Angle(0, 18, 0);
    ITEM.attachmentOffsetVector = Vector(-5.73, 4.38, 11.79);
ITEM:Register();